dataset: BrailleLetter
device: cuda
num_workers: 8
data_dir: /home/hershel/data/
model_path: checkpoints/mlpb_BL_20_200.pth
resume: False

T: 20
v_threshold: 1.0

input_dim: 4
hidden_dim: 200
classes: 28
net: fc
neuron_type: if
num_layers: 3


use_cupy: True
amp: False
batch_size: 8
loss_func: mse

training_method: sdfa
