dataset: dvs
device: cuda
num_workers: 8
data_dir: /home/hershel/data/
out_dir: ./optuna_logs
resume: False

T: 30
v_threshold: 1.0

classes: 11
net: conv
channels: 128
neuron_type: lif

use_cupy: True
amp: False
batch_size: 8
epochs: 300
optim: adam
loss_func: mse

lr: 1e-3
training_method: sdfa
