dataset: dvs
device: cuda
data_dir: /home/hershel/data/
out_dir: ./logs/
resume: False

T: 30
v_threshold: 1.0

classes: 11
net: vgg
channels: 512
neuron_type: if
num_workers: 16

use_cupy: True
amp: False
batch_size: 8
epochs: 300
optim: adam
weight_decay: 1e-3
loss_func: mse


lr: 1e-4
training_method: sdfa
