dataset: ncaltech
device: cuda
data_dir: /home/hershel/data/
out_dir: ./logs/
resume: False

T: 20
v_threshold: 1.0

classes: 101
net: conv
channels: 128
neuron_type: lif

amp: False
batch_size: 16
epochs: 200
optim: adam

lr: 1e-4
training_method: sdfa