dataset: shd
device: cuda
data_dir: /home/hershel/data/
model_path: checkpoints/mlpb_SHD_100_100.pth
resume: False

T: 100
v_threshold: 1.0

input_dim: 700
hidden_dim: 100
classes: 20
net: fc
neuron_type: if
num_layers: 3

use_cupy: True
amp: False
batch_size: 32
loss_func: mse

training_method: sdfa